package:
  name: hexmap
  version: 0.1

source:
  git_url: https://github.com/Xett/hexmap.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/Xett/hexmap.git
